# Generated by Django 5.1.4 on 2024-12-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_company_remove_job_date_posted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_url',
            new_name='employment_details',
        ),
        migrations.AddField(
            model_name='job',
            name='overview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
