# Generated by Django 5.1.4 on 2024-12-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_job_url_job_employment_details_job_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='overview',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
