# Generated by Django 5.1.4 on 2024-12-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_overview_alter_job_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employment_details',
            new_name='job_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
